### ISSUE TITLE
Employees at State Universites

### ISSUE THREAD

**Issue by SeanMarcia** [benbalter/gman#87]
I noticed that Gman doesn't validate `.edu` email addresses for state universities. Is this because of the potential for students to sign up?

A number of universities, mine included, have different domains for employee versus student emails. For example, at George Mason University employee emails are `@gmu.edu` and student emails are `@masonlive.gmu.edu`. I haven't dug into the gem to see if this type of stratification is possible but before I go about submitting a PR I wanted make sure there wasn't another reason that `.edu` was being excluded so I don't do some unwanted work. :)

**Comment by benbalter** [comment]
@SeanMarcia you are correct. The `.edu` TLD is blacklisted because it's largely non-government employees. https://github.com/leereilly/swot exists for the purpose of detecting educational domains, for students, faculty, and staff.

What's your immediate use case? For my use (and the vision of GMan), I don't know that adding faculty would make much sense. While government employees in the sense that they get a paycheck from a publicly funded university, they generally don't act like government employees, in the broader sense (see https://github.com/benbalter/gman/issues/16 for some additional context).

My gut reaction is that it'd be overburdensome to maintain, as SWOT already knows about tens of thousand of educational domains, and there's a deep rabbit hole of validating which universities are publicly funded, if the faculty member is an adjunct or staff, administrators, etc.

**Comment by SeanMarcia** [comment]
@benbalter Thanks for the quick reply!

I don't know if I have an "immediate use case." I'm a software developer at GMU and I had heard that 18F had built a [reverse auction site](http://reverseauctions.gsa.gov/reverseauctions/reverseauctions/) and since that is something that we are researching it seemed like a great place to start rather than reinventing the wheel ourselves. 

Unfortunately, they either haven't open sourced the code for it on github or it wasn't actually built by 18F. After looking around other repositories I couldn't find anything that fit the bill so my next thought was that I should join the github government group to suggest and start a project like this. It seemed to make sense to me since it is something other agencies could use because (in Virginia at least) we follow the same 508/ADA accessibility requirements as the federal government so whatever we built could be used by anyone who has the same requirements.

Which led me to attempt to join the government group on github and I wasn't able to validate myself as state government employee. 

I have emailed the gsa about the reverse auction site and if they have plans to open source it so if/when they reply my wanting to be validated with gman may end up as a moot topic anyway :)

**Comment by benbalter** [comment]
> I had heard that 18F had built a reverse auction site and since that is something that we are researching it seemed like a great place to start rather than reinventing the wheel ourselves.
> 
> Unfortunately, they either haven't open sourced the code for it on github or it wasn't actually built by 18F. 

@konklone @gbinal may be able to point you in the right direction.

**Comment by gbinal** [comment]
Hey @SeanMarcia.  Alas, it's a GSA project but it definitely wasn't us and we're not in a position to push to change that.  I def. support your asking them to opensource it but I'm not optimistic.
